apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wattwise-ai.fullname" . }}-config
  labels:
    {{- include "wattwise-ai.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "wattwise-ai.databaseUrl" . | quote }}
  BACKEND_URL: {{ include "wattwise-ai.backendUrl" . | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

