apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wattwise-ai.fullname" . }}-secrets
  labels:
    {{- include "wattwise-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}

